- lib/scholar/linear/logistic_regression.ex
Softmax in a `predict` function causes numerical errors, and since f(t) = exp(t) is strictly monotonical, it doesn't matter if we use softmax.
> Remove redundant softmax

- lib/scholar/covariance/covariance.ex
- lib/scholar/linear/logistic_regression.ex
- lib/scholar/metrics.ex
- lib/scholar/metrics/clustering.ex
- lib/scholar/metrics/distance.ex
- lib/scholar/preprocessing.ex
Closes #32 
As all the functions use now NimbleOptions I remove all the specs in Scholar.
> remove specs

- lib/scholar/cluster/gmm.ex
- test/scholar/cluster/gmm_test.exs
Added Gaussian Mixture Model implementation, similar to the one in scikit-learn Python module. Currently it supports only full covariances and uses k-means for the initialisation. Other covariance types (diagonal, tied, spherical) and initialisation methods (random, k-means++) can easily be added.
> Adding Gaussian Mixture Model

- lib/scholar/metrics/similarity.ex
- test/scholar/metrics/similarity_test.exs
Closes #149
I added the Dice coefficient and support for the option `axis` in Jaccard Similarity.
> Add Dice coefficient and upgrade Jaccard similarity

- lib/scholar/linear/linear_regression.ex
- lib/scholar/linear/ridge_regression.ex
- lib/scholar/metrics/regression.ex
- lib/scholar/model_selection.ex
- test/scholar/linear/linear_regression_test.exs
Closes #148 
I also added some minor improvements in linear and ridge regression
> Grid search

- lib/scholar/integrate/integrate.ex
I spotted an error when reading the docs.
> minor grammar fix in integrate/integrate.ex

- lib/scholar/naive_bayes/complement.ex
The URL has "moved"
```bash
curl -I https://www.aaai.org/Papers/ICML/2003/ICML03-081.pdf?ref=https://githubhelp.com
```
With a 301
```bash
HTTP/2 301
server: nginx
date: Thu, 28 Sep 2023 20:36:36 GMT
content-type: text/html
content-length: 162
location: https://aaai.org/Papers/ICML/2003/ICML03-081.pdf?ref=https://githubhelp.com
```
Which was nice of them, but unfortunately it moved againt
```bash
curl -I https://aaai.org/Papers/ICML/2003/ICML03-081.pdf?ref=https://githubhelp.com
```
As we get a 404 on that "moved" url
```bash
HTTP/2 404
server: nginx
date: Thu, 28 Sep 2023 20:37:14 GMT
content-type: text/html
content-length: 146
vary: Accept-Encoding
```
A duck-duck-go search for the URL is under a CDN now
```bash
curl -I https://cdn.aaai.org/ICML/2003/ICML03-081.pdf
```
Now with a 200 OK …
> Update URL reference to "Tackling the Poor Assumptions of Naive Bayes Text Classifiers" (ICML03-081.pdf)

- lib/scholar/metrics/classification.ex
- lib/scholar/options.ex
- test/scholar/metrics/classification_test.exs
Noticed that in #122 there was also the issue for `precision_recall_fscore_support` which was mainly done in #185.
> Add precision_recall_fscore_support function

- lib/scholar/metrics/classification.ex
I've noticed that it was possible to add katex notation to the documentation, so this PR improves the previous #185 documentation.
> Improve fbeta_score documentation

- lib/scholar/metrics/regression.ex
- test/scholar/metrics/regression_test.exs
This PR also adds the particular cases:
- `mean_poisson_deviance`
- `mean_gamma_deviance`
And updates `mean_square_error` to use `mean_tweedie_deviance` as well.
> Add mean_tweedie_deviance and particular cases

- lib/scholar/metrics/classification.ex
I based the implementation on [sklearn's](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.log_loss.html), with these main differences:
- Dropped labels as an optional argument, since it's mostly useful for string labels. Note as a result, the class index or class number of a value in `y_true` is always given by its ordered ranking over all `y_true` values (in the language of `sklearn`, the class index is always inferred). For example, if `y_true = [4, 0, 9, 4, 9]` the indices would be `[1, 0, 2, 1, 2]`. 
- No clipping of `y_prob` values to interval `(eps, 1-eps)`. That means `log(0)` can be evaluated to `-Inf` which would immediately cause a return of `Inf` for the function. I chose to keep this possibility because it immediately signals either that the client got inputs …
> Added log loss classification metric

- lib/scholar/metrics/regression.ex
- test/scholar/metrics/regression_test.exs
Following #193 adds another metric from #122.
> Add d2_tweedie_score

- lib/scholar/neighbors/kd_tree.ex
`indices` is a permutation, applying `argsort` to a permutation is the same as permutation inverse and we can compute it in linear time.
> Replace second order argsort with permutation inverse

- lib/scholar/neighbors/random_projection_forest.ex
- test/scholar/neighbors/random_projection_forest_test.exs
Changelog:
- Fixed the bug inside `predict/2` that assumed that query is of the same size as tensor used to grow the forest.
- Predict now returns the indices of (approximate) k-nearest neigbors as well as distances from the query points.
- ~~Hyperplanes and medians are now `f64`.~~
- Incorporated some feedback from #215 I didn't manage to before the pull request got closed. E.g. `left_child` and `right_child` are private now.
- Fixes https://github.com/elixir-nx/scholar/issues/230.
One thing I am still not sure about. `num_neighbors` is passed as an argument to `fit/2`. I prefer it like this, but it also makes sense to pass it as an argument to `predict/2`. There is also a small inconsistency with the option name used for the number of neighbors: [KNearestNeighbors uses …
> Random Projection Forest Update

- lib/scholar/metrics/regression.ex
- lib/scholar/options.ex
- test/scholar/metrics/regression_test.exs
The Mean Pinball Loss function for evaluation of prediction performance of regression models.
Listed in the functions to add[ in this issue](https://github.com/elixir-nx/scholar/issues/122).
I've adapted the implementation from `sklearn` and the relevant of that library are linked in the code, to give credit and serve as reference.
> Add Mean Pinball Loss function.

- lib/scholar/naive_bayes/multinomial.ex
- test/scholar/naive_bayes/multinomial_test.exs
Changelog:
- Removed `classes` property and `ordinal_encode` from `fit`.
- Updated docstring to specify that targets should be between 0 and `num_classes` - 1.
- Some refactoring, e.g. used `Nx.logsumexp`, moved argument validation inside `fit`, etc.
- Fixes #242.
> Multinomial Naive Bayes Improvements

- lib/scholar/neighbors/brute_knn.ex
- lib/scholar/shared.ex
- test/scholar/neighbors/brute_knn_test.exs
Implements brute-force k-NN search algorithm.
Closes #239.
> Brute k-NN

- lib/scholar/metrics/classification.ex
added det_curve function and doctests
> add det curve

- notebooks/nearest_neighbors.livemd
> Add livebook

- lib/scholar/linear/bayesian_ridge_regression.ex
- lib/scholar/linear/linear_helpers.ex
- lib/scholar/linear/linear_regression.ex
- lib/scholar/linear/polynomial_regression.ex
- lib/scholar/linear/ridge_regression.ex
- test/scholar/linear/bayesian_ridge_regression_test.exs
Implements the suggestion from [here](https://github.com/elixir-nx/scholar/issues/249).
I've had to revert the change suggested by @krstopro [here](https://github.com/elixir-nx/scholar/pull/247#discussion_r1573718068), as that change made some tests from `LinearRegression` and `RidgeRegression` fail.
When it comes to ` LinearRegression`  I believe those failures are related to the shape of the target data: 
- The tests yield failures when the data is 2 dimensional, [like a column vector](https://github.com/elixir-nx/scholar/blob/322687a04ea0f701efdf42fd6360627a0ed30518/test/scholar/linear/linear_regression_test.exs#L132)
- Flattening those data yield a passing test.
`RidgeRegression` tests fail with multi-output target data. These cannot be flattened.
> Unify weight handling and refactor linear models' helper functions

- notebooks/cv_gradient_boosting_tree.livemd
Removes setup cell that sets EXLA as default backend and compiler. This is not supported for EXGBoost at the time.
> use Nx.BinaryBackend for cv notebook

- lib/scholar/manifold/trimap.ex
- lib/scholar/neighbors/brute_knn.ex
- lib/scholar/neighbors/utils.ex
- notebooks/cv_gradient_boosting_tree.livemd
- test/scholar/manifold/trimap_test.exs
> Make nn algorithm configurable

- lib/scholar/decomposition/pca.ex
Fixes a bug inside `Scholar.Decomposition.PCA` where `Scholar.Decomposition.Utils.flip_svd/2` was used instead of `flip_svd/2` from the same module.
Closes #298
> Change `Utils.flip_svd/2` to `flip_svd/2` inside `Scholar.Decomposition.PCA`

- lib/scholar/cluster/optics.ex
Added:
- OPTICS clustering algorithm
- Its description
- doctests
Currently, the only available clustering method is dbscan, but I plan to add the xi method soon.
> Added OPTICS clustering algorithm

- lib/scholar/metrics/regression.ex
- test/scholar/metrics/regression_test.exs
Following up on #144 issue:
I've added batching to the `Regression` metrics, similar to the batching implemented in the `Distances` metrics. However, I'm not entirely sure if I fully understood the issue, so I would greatly appreciate any feedback.
I did not make changes to the following metrics:
- `mean_pinball_loss`
- `d2_absolute_error_score`
- `d2_pinball_score`
These metrics appear to already support batching through the `:multioutput` argument. If that's the case, perhaps we should consider standardizing the argument to `:axes` for consistency across similar functions.
Please let me know if I’m mistaken about anything.
> Added batching to regression metrics

- lib/scholar/feature_extraction/count_vectorizer.ex
- test/scholar/feature_extraction/count_vectorizer.ex
Hi I added `CountVectorizer` as it would be useful in pipeline with Naive Bayes algorithms that we already implemented (for example in spam detection)
> Add CountVectorizer
