elixir-nx/scholar

lib/scholar/metrics.ex
lib/scholar/spatial.ex
test/scholar/metrics_test.exs

Brings the Axon.Metrics module over, with some changes to the moduledoc (which had some motivations regarding training and NN specific terms)

feat(metrics): bring Axon.Metrics to Scholar.Metrics

---

lib/scholar/metrics.ex

Related to [issue](https://github.com/elixir-nx/scholar/issues/15)

Remove running average and running sum

---

lib/scholar/preprocessing.ex
test/scholar/preprocessing_test.exs

Add ordinal and one-hot encodings

---

lib/scholar/metrics.ex

Handle zero division in metrics

---

lib/scholar/cluster/k_means.ex
lib/scholar/interpolation/cubic_spline.ex
lib/scholar/linear/logistic_regression.ex
test/scholar/cluster/k_means_test.exs
test/scholar/interpolation/cubic_spline_test.exs
test/scholar/linear/logistic_regression_test.exs

Change train to fit

---

lib/scholar/covariance.ex

As we agreed in #65, separate implementation of correlation matrix.

Add correlation matrix

---

lib/scholar/naive_bayes/gaussian.ex
notebooks/k_means.livemd
notebooks/linear_regression.livemd

Except for KMeans, I added `Nx.Constants.pi()` and reformat some cells from the Linear Regression notebook.

Update KMeans notebook

---

lib/scholar/neighbors/k_nearest_neighbors.ex
lib/scholar/options.ex
test/scholar/neighbors/k_nearest_neighbors_test.exs

Add K-Nearest Neighbors

---

lib/scholar/linear/logistic_regression.ex

@seanmor5 this is my proposition according to your suggestions.

Cross Entropy from logits

---

mix.exs
notebooks/k_nearest_neighbors.livemd

Depends on #92 and [#1131](https://github.com/elixir-nx/nx/pull/1131)

Add Notebook about KNNs

---

lib/scholar/cluster/k_means.ex
lib/scholar/linear/linear_regression.ex
lib/scholar/linear/logistic_regression.ex
lib/scholar/metrics.ex
lib/scholar/metrics/clustering.ex
lib/scholar/metrics/distance.ex
lib/scholar/metrics/similarity.ex
lib/scholar/naive_bayes/complement.ex
lib/scholar/naive_bayes/gaussian.ex
lib/scholar/naive_bayes/multinomial.ex
lib/scholar/neighbors/k_nearest_neighbors.ex
lib/scholar/preprocessing.ex
lib/scholar/shared.ex
lib/scholar/stats.ex

Currently, we need to wait for Nx support for :bf16 and :f16 in SVD (Linear and Ridge Regression).

Improve types

---

lib/scholar/cluster/affinity_propagation.ex
lib/scholar/cluster/k_means.ex
lib/scholar/manifold/tsne.ex
lib/scholar/options.ex
test/scholar/cluster/affinity_propagation_test.exs
test/scholar/cluster/k_means_test.exs
test/scholar/manifold/tsne_test.exs

Add key as an option to seed

---

lib/scholar/impute/simple_imputer.ex
lib/scholar/neighbors/k_nearest_neighbors.ex
lib/scholar/neighbors/radius_nearest_neighbors.ex
test/scholar/neighbors/radius_nearest_neighbors_test.exs

Before we could add DBSCAN we have to support Radius Nearest Neighbors

Add Radius Nearest Neighbors

---

lib/scholar/metrics.ex
lib/scholar/shared.ex

Add average precision score

---

lib/scholar/metrics.ex

This adds some cool features, but has a small drawback. When user doesn't set weights the output will have float type instead of unsigned integer. But imo, it's still worth to add it.

Upgrade confusion matrix function

---

lib/scholar/integrate/integrate.ex
lib/scholar/manifold/tsne.ex
lib/scholar/metrics/distance.ex
lib/scholar/shared.ex

@seanmor5, let me know if this is sufficient in terms of distances. I will focus on classification metrics tomorrow.

Allow broadcast in distances

---

lib/scholar/metrics.ex

This PR is a continuation of the PR #72. 
I applied the requested changes.

Add r2_score based on requested changes.

---

lib/scholar/metrics/classification.ex
lib/scholar/metrics/regression.ex
lib/scholar/model_selection.ex
mix.exs
test/scholar/linear/logistic_regression_test.exs
test/scholar/metrics/classification_test.exs
test/scholar/metrics/regression_test.exs

Change the structure of metrics.ex

---

notebooks/cv_gradient_boosting_tree.livemd

Let me know if this is a good idea to present the recently added cross-validation utility. I was playing around with it and decided to create this notebook :) I also was planning to add an hyperparameter tuning section with Grid Search, but let me know your thoughts before I continue.
Source of notes: Book _Hands On Machine Learning_ by A. Geron.

Create notebook for CV presentation

---

lib/scholar/manifold/tsne.ex

I added the APA reference style for the t-SNE reference, which may be more suitable as a pure title only.

APA reference style for t-SNE

---

notebooks/cv_gradient_boosting_tree.livemd

- Use correct markup on hyperlinks
- Pass only training data to the grid search
- Add final evaluation on test set

Fix notebook markup and improvements

---

lib/scholar/metrics/classification.ex
test/scholar/metrics/classification_test.exs

Used expression:
$$F_\beta = (1 + \beta^2) \cdot \frac{\mathrm{precision} \cdot \mathrm{recall}}{(\beta^2 \cdot \mathrm{precision}) + \mathrm{recall}}$$
From https://en.wikipedia.org/wiki/F-score

F-beta score

---

lib/scholar/interpolation/cubic_spline.ex

Improve cubic interpolation

---

benchmarks/knn.exs
lib/scholar/neighbors/kd_tree.ex
test/scholar/neighbors/kd_tree_test.exs

I need to add a testing module and benchmarks, but as far as I've been testing it, it works fine, and is quick where classical KNN runs out of memory (100000x4) :))

Knn via kdtree

---

lib/scholar/metrics/ranking.ex

Added ndcg metric and doctests for it

Added ndcg metric

---

lib/scholar/metrics/regression.ex

Added d2_pinball_score and d2_absolute_error_score and doc tests for them

Added d2_pinball_score and d2_absolute_error_score

---

notebooks/cv_gradient_boosting_tree.livemd

Update EXGBoost to v0.5.1 (#273)

Update EXGBoost version in notebook

---

notebooks/manifold_learning.livemd

Not a big deal, but since it may be the first time people see Tucan, it's best to keep it compact (and more appealing) :)

Remove Tucan.layers/1 with a single layer

---

lib/scholar/cluster/affinity_propagation.ex
lib/scholar/cluster/dbscan.ex
lib/scholar/cluster/k_means.ex
lib/scholar/linear/ridge_regression.ex
lib/scholar/manifold/mds.ex
lib/scholar/manifold/trimap.ex
lib/scholar/neighbors/knn_classifier.ex
lib/scholar/neighbors/knn_regressor.ex
lib/scholar/neighbors/radius_nearest_neighbors.ex
lib/scholar/options.ex
lib/scholar/preprocessing/max_abs_scaler.ex
lib/scholar/preprocessing/one_hot_encoder.ex
lib/scholar/preprocessing/ordinal_encoder.ex
test/scholar/cluster/dbscan_test.exs
test/scholar/integrate/integrate_test.exs

Fix various typos and improve language
